name: Publish Mod to Thunderstore

# Run when changes are pushed to key files
on:
  workflow_dispatch:  # This enables manual triggering
  push:
    paths:
      - 'manifest.json'
      - 'BepInEx/plugins/ControllerSupport.dll'
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Use checkout to publish the files in your repo
      - uses: actions/checkout@v4
      
      # Extract version from manifest.json
      - name: Extract version from manifest
        id: get_version
        run: |
          VERSION=$(grep -o '"version_number": "[^"]*' manifest.json | cut -d'"' -f4)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "name=Controller_Support" >> $GITHUB_OUTPUT
      
      # Check if package already exists on Thunderstore
      - name: Check if package exists
        id: check_package
        run: |
          PACKAGE_URL="https://repo.thunderstore.io/api/v1/package/Pacmanninja998/Controller_Support/${{ steps.get_version.outputs.version }}/"
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$PACKAGE_URL")
          
          if [ "$HTTP_STATUS" == "200" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Package already exists on Thunderstore, will skip upload"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "Package doesn't exist yet, will proceed with upload"
          fi
      
      # Upload to Thunderstore (only if package doesn't exist)
      - name: Upload Thunderstore Package
        if: steps.check_package.outputs.exists != 'true'
        uses: GreenTF/upload-thunderstore-package@v4.3
        with:
          community: repo
          # Name of the team to publish the mod under
          namespace: Pacmanninja998
          # Name of the package
          name: Controller_Support
          # Package version to publish (from manifest.json)
          version: ${{ steps.get_version.outputs.version }}
          # Description of the mod
          description: "Use your Controller on R.E.P.O"
          # Thunderstore API token
          token: ${{ secrets.THUNDERSTORE_TOKEN }}
          # Website URL
          website: "https://github.com/Pacmanninja/R.E.P.O.ControllerSupport"
          # Dependencies
          deps: "bbepis-BepInExPack-5.4.2117"
          # Thunderstore repository URL
          repo: repo.thunderstore.io
          # Exclude .github directory and only include specific directories/files
          path: |
            BepInEx
            icon.png
            README.md
            manifest.json
            CHANGELOG.md
          # Categories for the mod
          categories: |
            mods
            tools
      
      - name: Package status
        run: |
          if [ "${{ steps.check_package.outputs.exists }}" == "true" ]; then
            echo "Package already exists on Thunderstore. No upload was attempted."
          else
            echo "Package upload was attempted. Check logs for results."
          fi
